inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'vendor/**/*'

Airbnb/OptArgParameters:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
